version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "18:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "nuget update"
      include: "scope"
    open-pull-requests-limit: 5
